### Fake News Classifier using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Deep Learning/NLP/Fake News Classifier using LSTM/train.csv')

In [3]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [4]:
## Drop nan values
df=df.dropna()

In [5]:
## Get Independent Features

X=df.drop('label', axis=1)

In [6]:
## Get Dependent Features
y=df['label']

In [7]:
X.shape

(18285, 4)

In [8]:
y.shape

(18285,)

In [9]:
import tensorflow as tf

In [10]:
tf.__version__

'2.7.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [12]:
## Vocabulary Size
voc_size=5000

**One_Hot Representation**

In [13]:
messages=X.copy()

In [15]:
messages['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [16]:
messages.reset_index(inplace=True)

In [17]:
messages

index  ...                                               text
0          0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1          1  ...  Ever get the feeling your life circles the rou...
2          2  ...  Why the Truth Might Get You Fired October 29, ...
3          3  ...  Videos 15 Civilians Killed In Single US Airstr...
4          4  ...  Print \nAn Iranian woman has been sentenced to...
...      ...  ...                                                ...
18280  20795  ...  Rapper T. I. unloaded on black celebrities who...
18281  20796  ...  When the Green Bay Packers lost to the Washing...
18282  20797  ...  The Macy’s of today grew from the union of sev...
18283  20798  ...  NATO, Russia To Hold Parallel Exercises In Bal...
18284  20799  ...    David Swanson is an author, activist, journa...

[18285 rows x 5 columns]

In [18]:
import nltk
import re

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [20]:
from nltk.corpus import stopwords

In [21]:
### Data Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [22]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [23]:
onehot_repr=[one_hot(words, voc_size) for words in corpus]
onehot_repr

[[584, 3556, 2932, 628, 2459, 252, 346, 1802, 2151, 477],
 [2968, 2468, 4515, 1197, 1997, 2103, 92],
 [536, 4762, 1634, 2021],
 [4584, 379, 1182, 4530, 975, 2025],
 [4719, 1997, 291, 595, 411, 3659, 1997, 4365, 3732, 2171],
 [718,
  3253,
  1950,
  3352,
  3250,
  275,
  222,
  4716,
  3507,
  2628,
  309,
  4977,
  4384,
  4543,
  92],
 [2462, 4480, 4491, 3986, 132, 3296, 2548, 3494, 1351, 4053, 4226],
 [1683, 683, 3156, 4048, 789, 1604, 275, 1568, 1351, 4053, 4226],
 [2535, 2622, 3525, 2064, 3836, 615, 2443, 3965, 275, 2092],
 [3531, 421, 2951, 2510, 1277, 3910, 3508, 3373],
 [35, 759, 4243, 1644, 2997, 1683, 2790, 566, 1740, 3447, 2647],
 [4530, 2625, 2459, 615, 275, 789],
 [2696, 150, 4201, 3892, 4865, 3820, 1139, 963, 2208],
 [3827, 2417, 3627, 3279, 2272, 2255, 1171, 1351, 4053, 4226],
 [2025, 4260, 2944, 2181, 1110, 1351, 4053, 4226],
 [4636, 1093, 797, 1966, 604, 2968, 2456, 4584, 4345, 2173],
 [3371, 2920, 2468],
 [4528, 4818, 4378, 3456, 275, 4002, 2683, 92],
 [2537, 3031, 45

Embedding Representation

In [24]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1802 2151  477]
 [   0    0    0 ... 1997 2103   92]
 [   0    0    0 ... 4762 1634 2021]
 ...
 [   0    0    0 ... 1351 4053 4226]
 [   0    0    0 ...  549 2159 1384]
 [   0    0    0 ...  523  252 4754]]


In [25]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  584,
       3556, 2932,  628, 2459,  252,  346, 1802, 2151,  477], dtype=int32)

In [26]:
## Creating Model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size, embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
len(embedded_docs),y.shape

(18285, (18285,))

In [29]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [30]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

Model Training

In [32]:
### Finally Training
model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 8s 16ms/step - loss: 0.3425 - accuracy: 0.8388 - val_loss: 0.1926 - val_accuracy: 0.9152
Epoch 2/10
192/192 [==============================] - 3s 14ms/step - loss: 0.1423 - accuracy: 0.9424 - val_loss: 0.1910 - val_accuracy: 0.9198
Epoch 3/10
192/192 [==============================] - 3s 14ms/step - loss: 0.1010 - accuracy: 0.9635 - val_loss: 0.2227 - val_accuracy: 0.9150
Epoch 4/10
192/192 [==============================] - 2s 12ms/step - loss: 0.0765 - accuracy: 0.9738 - val_loss: 0.2452 - val_accuracy: 0.9165
Epoch 5/10
192/192 [==============================] - 2s 12ms/step - loss: 0.0614 - accuracy: 0.9797 - val_loss: 0.2801 - val_accuracy: 0.9138
Epoch 6/10
192/192 [==============================] - 3s 14ms/step - loss: 0.0433 - accuracy: 0.9868 - val_loss: 0.3674 - val_accuracy: 0.9065
Epoch 7/10
192/192 [==============================] - 3s 14ms/step - loss: 0.0345 - accuracy: 0.9895 - val_loss: 0.3923 - val_accuracy: 0.9085

Performance Metrics And Accuracy

## If you are using TensorFlow version 2.5, you will receive the following warning:
tensorflow\python\keras\engine\sequential.py:455: UserWarning: model.predict_classes() is deprecated and will be removed after 2021-01-01. Please use instead:
* np.argmax(model.predict(x), axis=-1), if your model does multi-class classification (e.g. if it uses a softmax last-layer activation).
* (model.predict(x) > 0.5).astype("int32"), if your model does binary classification (e.g. if it uses a sigmoid last-layer activation).

In [34]:
y_pred=(model.predict(X_test) > 0.5).astype("int32")

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test, y_pred)

array([[3083,  336],
       [ 226, 2390]])

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9068765534382767