## Fake News Classifier using Bidirectional LSTM (NLP)

Problem Statement: We are going to use "Title" to classify our News is Fake or Real,So "title" is our Independent variable,whereas our target is to detect our News is Fake or Not,So here our dependent/target variable is label,So Let's get the Independent & Dependent variable

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Deep Learning/NLP/Fake News Classifier using LSTM/train.csv')

In [ ]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
## Drop nan values
df=df.dropna()

In [ ]:
## Get Independent Features
X=df.drop('label', axis=1)

In [ ]:
y=df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

In [ ]:
from typing import Sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [ ]:
# Vocabulary Size
voc_size=5000

Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages[['title','author','text']]

title  ...                                               text
0      House Dem Aide: We Didn’t Even See Comey’s Let...  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...  ...  Ever get the feeling your life circles the rou...
2                      Why the Truth Might Get You Fired  ...  Why the Truth Might Get You Fired October 29, ...
3      15 Civilians Killed In Single US Airstrike Hav...  ...  Videos 15 Civilians Killed In Single US Airstr...
4      Iranian woman jailed for fictional unpublished...  ...  Print \nAn Iranian woman has been sentenced to...
...                                                  ...  ...                                                ...
20795  Rapper T.I.: Trump a ’Poster Child For White S...  ...  Rapper T. I. unloaded on black celebrities who...
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...  ...  When the Green Bay Packers lost to the Washing...
20797  Macy’s Is Said to Receive Takeover Approach by...  ...  The Macy’s of today grew from the union of sev...
20798  NATO, Russia To Hold Parallel Exercises In Bal...  ...  NATO, Russia To Hold Parallel Exercises In Bal...
20799                          What Keeps the F-35 Alive  ...    David Swanson is an author, activist, journa...

[18285 rows x 3 columns]

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
## msg=messages.loc[:,['title','author','text']] #You can use loc to select all rows but only a specific number of columns

In [ ]:
## msg.iloc[1]   #The iloc function allows you to subset pandas DataFrames based on their position or index.

In [ ]:
## Dataset Preprocessing
from nltk.stem.porter import PorterStemmer #Stemming is the process of reducing inflection in words to their root forms such as mapping a group of words to the same stem even if the stem itself is not a valid word in the Language.
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words, voc_size) for words in corpus]
onehot_repr

[[864, 2464, 2213, 952, 4393, 4174, 1290, 1952, 4551, 451],
 [2740, 3556, 3440, 1147, 3619, 4169, 963],
 [2921, 4730, 180, 1224],
 [4830, 1309, 502, 1836, 1062, 3401],
 [2685, 3619, 2087, 3097, 1062, 1815, 3619, 4005, 1793, 1357],
 [596,
  811,
  4484,
  1363,
  1839,
  1372,
  1651,
  2740,
  198,
  2030,
  4438,
  1555,
  2741,
  553,
  963],
 [2504, 707, 1955, 2109, 1223, 4836, 4152, 82, 1470, 1023, 814],
 [3228, 2912, 72, 3100, 743, 3854, 1372, 136, 1470, 1023, 814],
 [4228, 4847, 836, 756, 4859, 1414, 360, 1352, 1372, 2493],
 [4416, 1163, 2818, 1543, 736, 2055, 3805, 1201],
 [2113, 4093, 4063, 2948, 3659, 2984, 3330, 2715, 2794, 2863, 4279],
 [1836, 3580, 4393, 1414, 1372, 743],
 [589, 1394, 1009, 813, 2807, 2002, 796, 2473, 4469],
 [3605, 2660, 1846, 4800, 1881, 40, 1251, 1470, 1023, 814],
 [313, 2309, 4145, 3001, 2340, 1470, 1023, 814],
 [3972, 2910, 4331, 3553, 4569, 330, 4507, 4244, 850, 4756],
 [127, 3824, 3556],
 [1284, 3011, 2575, 3570, 1372, 866, 1549, 963],
 [4623, 2314, 

In [ ]:
sent_length=30
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 1952 4551  451]
 [   0    0    0 ... 3619 4169  963]
 [   0    0    0 ... 4730  180 1224]
 ...
 [   0    0    0 ... 1470 1023  814]
 [   0    0    0 ... 2734 3390 2031]
 [   0    0    0 ... 1701 1856 3059]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,  864, 2464,
       2213,  952, 4393, 4174, 1290, 1952, 4551,  451], dtype=int32)

In [ ]:
from tensorflow.keras.layers import Bidirectional
#from tensorflow.python.keras.layers.wrappers import Bidirectional
## Creating Model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
#model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 30, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs), y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 30), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
# Finally Training
model1.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
192/192 [==============================] - 15s 33ms/step - loss: 0.3609 - accuracy: 0.8202 - val_loss: 0.2102 - val_accuracy: 0.9079
Epoch 2/10
192/192 [==============================] - 5s 25ms/step - loss: 0.1533 - accuracy: 0.9404 - val_loss: 0.1954 - val_accuracy: 0.9173
Epoch 3/10
192/192 [==============================] - 5s 28ms/step - loss: 0.1047 - accuracy: 0.9609 - val_loss: 0.2190 - val_accuracy: 0.9210
Epoch 4/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0688 - accuracy: 0.9753 - val_loss: 0.2463 - val_accuracy: 0.9201
Epoch 5/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0463 - accuracy: 0.9852 - val_loss: 0.2805 - val_accuracy: 0.9157
Epoch 6/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0276 - accuracy: 0.9921 - val_loss: 0.3422 - val_accuracy: 0.9122
Epoch 7/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0184 - accuracy: 0.9952 - val_loss: 0.3811 - val_accuracy: 0.911

Performance Metrics and Accuracy

In [ ]:
y_pred1=(model1.predict(X_test) > 0.5).astype("int32")

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred1)

array([[3096,  323],
       [ 254, 2362]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.9043910521955261

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91      3419
           1       0.88      0.90      0.89      2616

    accuracy                           0.90      6035
   macro avg       0.90      0.90      0.90      6035
weighted avg       0.90      0.90      0.90      6035

